import type { ClinicT } from "@/lib/types";
import type { ListingStatus } from "@/lib/directory/listing-status";
import {
  auditDirectoryClinics,
  sanitizePreviewClinic,
} from "@/lib/directory/validate-clinic";

/**
 * Preview clinic directory dataset.
 *
 * - Demo rows: fictional profiles for UI preview. Never claimable. Clearly labeled.
 * - Unclaimed rows: only allowed when a real public source URL exists.
 *
 * Records previously stored as unclaimed with example.com placeholders are
 * sanitized to demo at export time until real public sources are attached.
 *
 * Do not fabricate credentials, reviews, outcomes, or Novalyte partnerships.
 */

export type PreviewClinic = ClinicT & {
  listingStatus: ListingStatus;
  latitude: number | null;
  longitude: number | null;
  dataSource: "public_web" | "demo";
  sourceUrl: string | null;
  lastReviewedAt: string | null;
  financingAvailable: boolean | null;
  inPersonAvailable: boolean | null;
  sameDayConsultations: boolean | null;
};

function treatmentRows(clinicId: string, specialties: string): ClinicT["treatments"] {
  return specialties.split(",").map((name, i) => ({
    id: `${clinicId}-tx-${i + 1}`,
    clinicId,
    name: name.trim(),
    category: name.trim(),
    description: null,
    concerns: null,
    priceRange: null,
    labRequired: false,
    consultRequired: true,
    careFormat: null,
  }));
}

export const PREVIEW_UNCLAIMED_CLINICS: PreviewClinic[] = [
  {
    id: "preview-unclaimed-01",
    name: "Bay Area Men's Health",
    slug: "bay-area-mens-health-sf",
    tagline: null,
    overview: "Independent men's health clinic in San Francisco advertising hormone evaluation and testosterone therapy. Public listing compiled from available business information.",
    logoColor: "teal",
    city: "San Francisco",
    state: "CA",
    zip: "94102",
    serviceArea: "San Francisco metro",
    specialties: "Testosterone Replacement Therapy, Hormone Optimization, Preventive Men's Health",
    capabilities: "On-site Lab/Phlebotomy",
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/bay-area-mens-health",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 35,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: true,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 37.7749,
    longitude: -122.4194,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/bay-area-mens-health",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-01-loc-1", clinicId: "preview-unclaimed-01", name: "Primary location", address: "San Francisco, CA 94102", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: true, phlebotomy: true, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-01", "Testosterone Replacement Therapy, Hormone Optimization, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-02",
    name: "Pacific Hormone Center",
    slug: "pacific-hormone-center-la",
    tagline: null,
    overview: "Los Angeles practice listing hormone optimization and men's sexual wellness services on its public website.",
    logoColor: "emerald",
    city: "Los Angeles",
    state: "CA",
    zip: "90024",
    serviceArea: "Los Angeles metro",
    specialties: "Hormone Optimization, Testosterone Replacement Therapy, Sexual Wellness",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/pacific-hormone-center",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 43,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 34.0522,
    longitude: -118.2437,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/pacific-hormone-center",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-02-loc-1", clinicId: "preview-unclaimed-02", name: "Primary location", address: "Los Angeles, CA 90024", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-02", "Hormone Optimization, Testosterone Replacement Therapy, Sexual Wellness"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-03",
    name: "Beverly Hills Wellness MD",
    slug: "beverly-hills-wellness-md",
    tagline: null,
    overview: "Beverly Hills clinic publicly advertising longevity and preventive men's health consultations.",
    logoColor: "sky",
    city: "Beverly Hills",
    state: "CA",
    zip: "90210",
    serviceArea: "Beverly Hills metro",
    specialties: "Longevity Medicine, Hormone Optimization, Preventive Men's Health",
    capabilities: null,
    telehealth: false,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/beverly-hills-wellness",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 51,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 34.0736,
    longitude: -118.4004,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/beverly-hills-wellness",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-03-loc-1", clinicId: "preview-unclaimed-03", name: "Primary location", address: "Beverly Hills, CA 90210", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-03", "Longevity Medicine, Hormone Optimization, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-04",
    name: "Coastal Men's Clinic",
    slug: "coastal-mens-clinic-sd",
    tagline: null,
    overview: "San Diego men's clinic listing ED care and testosterone therapy among publicly advertised services.",
    logoColor: "violet",
    city: "San Diego",
    state: "CA",
    zip: "92101",
    serviceArea: "San Diego metro",
    specialties: "Erectile Dysfunction, Sexual Wellness, Testosterone Replacement Therapy",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/coastal-mens-clinic",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: false,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 59,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 32.7157,
    longitude: -117.1611,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/coastal-mens-clinic",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-04-loc-1", clinicId: "preview-unclaimed-04", name: "Primary location", address: "San Diego, CA 92101", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-04", "Erectile Dysfunction, Sexual Wellness, Testosterone Replacement Therapy"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-05",
    name: "Capitol Men's Health",
    slug: "capitol-mens-health-sac",
    tagline: null,
    overview: "Sacramento clinic advertising medical weight-loss and GLP-1 programs on public channels.",
    logoColor: "amber",
    city: "Sacramento",
    state: "CA",
    zip: "95814",
    serviceArea: "Sacramento metro",
    specialties: "Medical Weight Loss, GLP-1 Programs, Preventive Men's Health",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/capitol-mens-health",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 67,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 38.5816,
    longitude: -121.4944,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/capitol-mens-health",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-05-loc-1", clinicId: "preview-unclaimed-05", name: "Primary location", address: "Sacramento, CA 95814", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-05", "Medical Weight Loss, GLP-1 Programs, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-06",
    name: "Manhattan Men's Care",
    slug: "manhattan-mens-care",
    tagline: null,
    overview: "New York City men's care practice listing TRT, ED care, and telehealth consultations.",
    logoColor: "rose",
    city: "New York",
    state: "NY",
    zip: "10001",
    serviceArea: "New York metro",
    specialties: "Testosterone Replacement Therapy, Erectile Dysfunction, Telehealth Consultations",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/manhattan-mens-care",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 35,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: true,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "NY",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 40.7128,
    longitude: -74.006,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/manhattan-mens-care",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-06-loc-1", clinicId: "preview-unclaimed-06", name: "Primary location", address: "New York, NY 10001", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-06", "Testosterone Replacement Therapy, Erectile Dysfunction, Telehealth Consultations"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-07",
    name: "Hudson Hormone Associates",
    slug: "hudson-hormone-nyc",
    tagline: null,
    overview: "Midtown New York practice advertising hormone and longevity-oriented consultations.",
    logoColor: "teal",
    city: "New York",
    state: "NY",
    zip: "10016",
    serviceArea: "New York metro",
    specialties: "Hormone Optimization, Longevity Medicine, Peptide-related Care",
    capabilities: "On-site Lab/Phlebotomy",
    telehealth: false,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/hudson-hormone",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 43,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "NY",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 40.7128,
    longitude: -74.006,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/hudson-hormone",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-07-loc-1", clinicId: "preview-unclaimed-07", name: "Primary location", address: "New York, NY 10016", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: true, phlebotomy: true, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-07", "Hormone Optimization, Longevity Medicine, Peptide-related Care"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-08",
    name: "Austin Performance Health",
    slug: "austin-performance-health",
    tagline: null,
    overview: "Austin clinic listing performance medicine, TRT, and weight-management programs.",
    logoColor: "emerald",
    city: "Austin",
    state: "TX",
    zip: "78701",
    serviceArea: "Austin metro",
    specialties: "Performance Medicine, Testosterone Replacement Therapy, Medical Weight Loss",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/austin-performance",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: false,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 51,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "TX",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 30.2672,
    longitude: -97.7431,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/austin-performance",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-08-loc-1", clinicId: "preview-unclaimed-08", name: "Primary location", address: "Austin, TX 78701", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-08", "Performance Medicine, Testosterone Replacement Therapy, Medical Weight Loss"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-09",
    name: "Texas Men's Wellness",
    slug: "texas-mens-wellness-dallas",
    tagline: null,
    overview: "Dallas men's wellness clinic publicly advertising ED, sexual wellness, and hair restoration services.",
    logoColor: "sky",
    city: "Dallas",
    state: "TX",
    zip: "75201",
    serviceArea: "Dallas metro",
    specialties: "Erectile Dysfunction, Sexual Wellness, Hair Restoration",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/texas-mens-wellness",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 59,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "TX",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 32.7767,
    longitude: -96.797,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/texas-mens-wellness",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-09-loc-1", clinicId: "preview-unclaimed-09", name: "Primary location", address: "Dallas, TX 75201", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-09", "Erectile Dysfunction, Sexual Wellness, Hair Restoration"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-10",
    name: "Houston Metro Men's Health",
    slug: "houston-metro-mens",
    tagline: null,
    overview: "Houston clinic listing testosterone therapy and preventive men's health services.",
    logoColor: "violet",
    city: "Houston",
    state: "TX",
    zip: "77002",
    serviceArea: "Houston metro",
    specialties: "Testosterone Replacement Therapy, Hormone Optimization, Preventive Men's Health",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/houston-metro-mens",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 67,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "TX",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 29.7604,
    longitude: -95.3698,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/houston-metro-mens",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-10-loc-1", clinicId: "preview-unclaimed-10", name: "Primary location", address: "Houston, TX 77002", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-10", "Testosterone Replacement Therapy, Hormone Optimization, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-11",
    name: "Miami Shore Men's Clinic",
    slug: "miami-shore-mens",
    tagline: null,
    overview: "Miami clinic advertising sexual wellness, ED care, and telehealth options.",
    logoColor: "amber",
    city: "Miami",
    state: "FL",
    zip: "33131",
    serviceArea: "Miami metro",
    specialties: "Sexual Wellness, Erectile Dysfunction, Telehealth Consultations",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/miami-shore-mens",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 35,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: true,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "FL",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 25.7617,
    longitude: -80.1918,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/miami-shore-mens",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-11-loc-1", clinicId: "preview-unclaimed-11", name: "Primary location", address: "Miami, FL 33131", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-11", "Sexual Wellness, Erectile Dysfunction, Telehealth Consultations"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-12",
    name: "Tampa Bay Hormone Clinic",
    slug: "tampa-bay-hormone",
    tagline: null,
    overview: "Tampa practice listing hormone optimization and longevity-oriented care.",
    logoColor: "rose",
    city: "Tampa",
    state: "FL",
    zip: "33602",
    serviceArea: "Tampa metro",
    specialties: "Hormone Optimization, Testosterone Replacement Therapy, Longevity Medicine",
    capabilities: null,
    telehealth: false,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/tampa-bay-hormone",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: false,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 43,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "FL",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 27.9506,
    longitude: -82.4572,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/tampa-bay-hormone",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-12-loc-1", clinicId: "preview-unclaimed-12", name: "Primary location", address: "Tampa, FL 33602", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-12", "Hormone Optimization, Testosterone Replacement Therapy, Longevity Medicine"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-13",
    name: "Desert Men's Health Phoenix",
    slug: "phoenix-desert-mens",
    tagline: null,
    overview: "Phoenix clinic advertising GLP-1 weight-loss programs and testosterone therapy.",
    logoColor: "teal",
    city: "Phoenix",
    state: "AZ",
    zip: "85004",
    serviceArea: "Phoenix metro",
    specialties: "Medical Weight Loss, GLP-1 Programs, Testosterone Replacement Therapy",
    capabilities: "On-site Lab/Phlebotomy",
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/desert-mens-phoenix",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 51,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "AZ",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 33.4484,
    longitude: -112.074,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/desert-mens-phoenix",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-13-loc-1", clinicId: "preview-unclaimed-13", name: "Primary location", address: "Phoenix, AZ 85004", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: true, phlebotomy: true, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-13", "Medical Weight Loss, GLP-1 Programs, Testosterone Replacement Therapy"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-14",
    name: "Scottsdale Longevity MD",
    slug: "scottsdale-longevity-md",
    tagline: null,
    overview: "Scottsdale practice publicly listing longevity and peptide-related care offerings.",
    logoColor: "emerald",
    city: "Scottsdale",
    state: "AZ",
    zip: "85251",
    serviceArea: "Scottsdale metro",
    specialties: "Longevity Medicine, Peptide-related Care, Preventive Men's Health",
    capabilities: null,
    telehealth: false,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/scottsdale-longevity",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 59,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "AZ",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 33.4942,
    longitude: -111.9261,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/scottsdale-longevity",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-14-loc-1", clinicId: "preview-unclaimed-14", name: "Primary location", address: "Scottsdale, AZ 85251", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-14", "Longevity Medicine, Peptide-related Care, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-15",
    name: "Vegas Men's Performance",
    slug: "vegas-mens-performance",
    tagline: null,
    overview: "Las Vegas clinic advertising performance medicine, ED care, and hair restoration.",
    logoColor: "sky",
    city: "Las Vegas",
    state: "NV",
    zip: "89109",
    serviceArea: "Las Vegas metro",
    specialties: "Performance Medicine, Erectile Dysfunction, Hair Restoration",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/vegas-mens-performance",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 67,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "NV",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 36.1699,
    longitude: -115.1398,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/vegas-mens-performance",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-15-loc-1", clinicId: "preview-unclaimed-15", name: "Primary location", address: "Las Vegas, NV 89109", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-15", "Performance Medicine, Erectile Dysfunction, Hair Restoration"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-16",
    name: "Lakeshore Men's Health Chicago",
    slug: "chicago-lakeshore-mens",
    tagline: null,
    overview: "Chicago men's health clinic listing TRT, hormone optimization, and telehealth.",
    logoColor: "violet",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    serviceArea: "Chicago metro",
    specialties: "Testosterone Replacement Therapy, Hormone Optimization, Telehealth Consultations",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/lakeshore-mens-chicago",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: false,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 35,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: true,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "IL",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 41.8781,
    longitude: -87.6298,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/lakeshore-mens-chicago",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-16-loc-1", clinicId: "preview-unclaimed-16", name: "Primary location", address: "Chicago, IL 60611", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-16", "Testosterone Replacement Therapy, Hormone Optimization, Telehealth Consultations"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-17",
    name: "Midwest Men's Wellness",
    slug: "chicago-midwest-wellness",
    tagline: null,
    overview: "Chicago clinic advertising medical weight loss and preventive men's health services.",
    logoColor: "amber",
    city: "Chicago",
    state: "IL",
    zip: "60654",
    serviceArea: "Chicago metro",
    specialties: "Medical Weight Loss, GLP-1 Programs, Preventive Men's Health",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/midwest-mens-wellness",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 43,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "IL",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 41.8781,
    longitude: -87.6298,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/midwest-mens-wellness",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-17-loc-1", clinicId: "preview-unclaimed-17", name: "Primary location", address: "Chicago, IL 60654", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-17", "Medical Weight Loss, GLP-1 Programs, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-18",
    name: "Peachtree Men's Clinic",
    slug: "atlanta-peachtree-mens",
    tagline: null,
    overview: "Atlanta clinic listing ED care, sexual wellness, and testosterone therapy.",
    logoColor: "rose",
    city: "Atlanta",
    state: "GA",
    zip: "30308",
    serviceArea: "Atlanta metro",
    specialties: "Erectile Dysfunction, Sexual Wellness, Testosterone Replacement Therapy",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/peachtree-mens",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 51,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "GA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 33.749,
    longitude: -84.388,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/peachtree-mens",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-18-loc-1", clinicId: "preview-unclaimed-18", name: "Primary location", address: "Atlanta, GA 30308", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-18", "Erectile Dysfunction, Sexual Wellness, Testosterone Replacement Therapy"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-19",
    name: "Southern Longevity Atlanta",
    slug: "atlanta-southern-longevity",
    tagline: null,
    overview: "Atlanta longevity-focused practice advertising hormone and preventive care.",
    logoColor: "teal",
    city: "Atlanta",
    state: "GA",
    zip: "30326",
    serviceArea: "Atlanta metro",
    specialties: "Longevity Medicine, Hormone Optimization, Preventive Men's Health",
    capabilities: "On-site Lab/Phlebotomy",
    telehealth: false,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/southern-longevity-atlanta",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 59,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "GA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 33.749,
    longitude: -84.388,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/southern-longevity-atlanta",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-19-loc-1", clinicId: "preview-unclaimed-19", name: "Primary location", address: "Atlanta, GA 30326", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: true, phlebotomy: true, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-19", "Longevity Medicine, Hormone Optimization, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-20",
    name: "Westside Metabolic Clinic",
    slug: "la-westside-weight",
    tagline: null,
    overview: "West Los Angeles clinic advertising GLP-1 and medical weight-loss programs.",
    logoColor: "emerald",
    city: "Los Angeles",
    state: "CA",
    zip: "90025",
    serviceArea: "Los Angeles metro",
    specialties: "Medical Weight Loss, GLP-1 Programs, Preventive Men's Health",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/westside-metabolic",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: false,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 67,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 34.0522,
    longitude: -118.2437,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/westside-metabolic",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-20-loc-1", clinicId: "preview-unclaimed-20", name: "Primary location", address: "Los Angeles, CA 90025", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-20", "Medical Weight Loss, GLP-1 Programs, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-21",
    name: "Golden Gate Telehealth Men's Care",
    slug: "sf-telehealth-mens",
    tagline: null,
    overview: "San Francisco\u2013based telehealth men's care listing virtual TRT and ED consultations.",
    logoColor: "sky",
    city: "San Francisco",
    state: "CA",
    zip: "94107",
    serviceArea: "San Francisco metro",
    specialties: "Telehealth Consultations, Testosterone Replacement Therapy, Erectile Dysfunction",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/golden-gate-telehealth",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 35,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: true,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 37.7749,
    longitude: -122.4194,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/golden-gate-telehealth",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-21-loc-1", clinicId: "preview-unclaimed-21", name: "Primary location", address: "San Francisco, CA 94107", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-21", "Telehealth Consultations, Testosterone Replacement Therapy, Erectile Dysfunction"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-22",
    name: "Empire Hair Restoration NYC",
    slug: "nyc-hair-restore",
    tagline: null,
    overview: "New York clinic publicly advertising hair restoration services for men.",
    logoColor: "violet",
    city: "New York",
    state: "NY",
    zip: "10022",
    serviceArea: "New York metro",
    specialties: "Hair Restoration, Preventive Men's Health",
    capabilities: null,
    telehealth: false,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/empire-hair-nyc",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 43,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "NY",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 40.7128,
    longitude: -74.006,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/empire-hair-nyc",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-22-loc-1", clinicId: "preview-unclaimed-22", name: "Primary location", address: "New York, NY 10022", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-22", "Hair Restoration, Preventive Men's Health"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-23",
    name: "North Dallas Peptide Wellness",
    slug: "dallas-peptide-wellness",
    tagline: null,
    overview: "Dallas clinic listing peptide-related and longevity-oriented consultations.",
    logoColor: "amber",
    city: "Dallas",
    state: "TX",
    zip: "75230",
    serviceArea: "Dallas metro",
    specialties: "Peptide-related Care, Longevity Medicine, Hormone Optimization",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/north-dallas-peptide",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 51,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "TX",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 32.7767,
    longitude: -96.797,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/north-dallas-peptide",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-23-loc-1", clinicId: "preview-unclaimed-23", name: "Primary location", address: "Dallas, TX 75230", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-23", "Peptide-related Care, Longevity Medicine, Hormone Optimization"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-24",
    name: "South Florida GLP-1 Center",
    slug: "miami-glp1-center",
    tagline: null,
    overview: "Miami clinic advertising GLP-1 programs with telehealth follow-up options.",
    logoColor: "rose",
    city: "Miami",
    state: "FL",
    zip: "33139",
    serviceArea: "Miami metro",
    specialties: "GLP-1 Programs, Medical Weight Loss, Telehealth Consultations",
    capabilities: null,
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/south-florida-glp1",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: false,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 59,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "FL",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 25.7617,
    longitude: -80.1918,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/south-florida-glp1",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: false,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-24-loc-1", clinicId: "preview-unclaimed-24", name: "Primary location", address: "Miami, FL 33139", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-24", "GLP-1 Programs, Medical Weight Loss, Telehealth Consultations"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-25",
    name: "Phoenix Sexual Wellness Center",
    slug: "phoenix-sexual-wellness",
    tagline: null,
    overview: "Phoenix clinic listing sexual wellness and ED care among public services.",
    logoColor: "teal",
    city: "Phoenix",
    state: "AZ",
    zip: "85016",
    serviceArea: "Phoenix metro",
    specialties: "Sexual Wellness, Erectile Dysfunction, Hormone Optimization",
    capabilities: "On-site Lab/Phlebotomy",
    telehealth: true,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/phoenix-sexual-wellness",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 67,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: null,
    statesServed: "AZ",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 33.4484,
    longitude: -112.074,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/phoenix-sexual-wellness",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-25-loc-1", clinicId: "preview-unclaimed-25", name: "Primary location", address: "Phoenix, AZ 85016", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: true, phlebotomy: true, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-25", "Sexual Wellness, Erectile Dysfunction, Hormone Optimization"),
    reviews: [],
  },
  {
    id: "preview-unclaimed-26",
    name: "San Diego Preventive Men's Care",
    slug: "sd-preventive-mens",
    tagline: null,
    overview: "San Diego practice advertising preventive men's health and primary-care style visits.",
    logoColor: "emerald",
    city: "San Diego",
    state: "CA",
    zip: "92103",
    serviceArea: "San Diego metro",
    specialties: "Preventive Men's Health, Men's Primary Care, Hormone Optimization",
    capabilities: null,
    telehealth: false,
    providerTypes: null,
    phone: null,
    email: null,
    website: "https://example.com/public-directory/sd-preventive-mens",
    bookingUrl: null,
    hours: null,
    verified: false,
    verificationStatus: "not_verified",
    acceptingNewPatients: true,
    claimStatus: "unclaimed",
    listingStatus: "unclaimed",
    profileCompleteness: 35,
    initialConsultPrice: null,
    membershipPrice: null,
    insuranceAccepted: true,
    hsaFsaAccepted: false,
    earliestAvailability: null,
    statesServed: "CA",
    languages: "English",
    accessibility: "Not publicly listed",
    pricingStatus: "consult",
    whatToExpect: null,
    latitude: 32.7157,
    longitude: -117.1611,
    dataSource: "public_web",
    sourceUrl: "https://example.com/public-directory/sd-preventive-mens",
    lastReviewedAt: "2026-07-15",
    financingAvailable: null,
    inPersonAvailable: true,
    sameDayConsultations: null,
    locations: [{ id: "preview-unclaimed-26-loc-1", clinicId: "preview-unclaimed-26", name: "Primary location", address: "San Diego, CA 92103", phone: null, hours: null, parking: null, transit: null, accessibility: "Not publicly listed", onSiteLab: false, phlebotomy: false, earliestAppt: null }],
    providers: [],
    treatments: treatmentRows("preview-unclaimed-26", "Preventive Men's Health, Men's Primary Care, Hormone Optimization"),
    reviews: [],
  },
];

export const PREVIEW_DEMO_CLINICS: PreviewClinic[] = [
  {
    id: "preview-demo-01",
    name: "Novalyte Men's Health \u2014 San Francisco",
    slug: "novalyte-mens-health-sf",
    tagline: "Demonstration clinic profile",
    overview: "Demonstration profile showcasing a full-featured men's health clinic card and profile experience. This demonstration profile is fictional and is shown only to preview the Novalyte AI clinic directory experience.",
    logoColor: "teal",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    serviceArea: "San Francisco and surrounding metro",
    specialties: "Testosterone Replacement Therapy, Hormone Optimization, Telehealth Consultations, Preventive Men's Health",
    capabilities: "On-site Lab/Phlebotomy, Financing available",
    telehealth: true,
    providerTypes: "Physician, Nurse Practitioner",
    phone: "(555) 010-1000",
    email: "demo@novalyte.example",
    website: null,
    bookingUrl: null,
    hours: "Mon\u2013Fri 8am\u20136pm PT",
    verified: false,
    verificationStatus: "demo",
    acceptingNewPatients: true,
    claimStatus: "not_claimable",
    listingStatus: "demo",
    profileCompleteness: 92,
    initialConsultPrice: 149,
    membershipPrice: 99,
    insuranceAccepted: true,
    hsaFsaAccepted: true,
    earliestAvailability: "Same-day telehealth consults available",
    statesServed: "CA",
    languages: "English, Spanish",
    accessibility: "Wheelchair accessible waiting area",
    pricingStatus: "published",
    whatToExpect: "Demonstration itinerary: intake, clinician consult, optional labs, care plan discussion.",
    latitude: 37.7749,
    longitude: -122.4194,
    dataSource: "demo",
    sourceUrl: null,
    lastReviewedAt: "2026-07-20",
    financingAvailable: true,
    inPersonAvailable: true,
    sameDayConsultations: true,
    locations: [{ id: "preview-demo-01-loc-1", clinicId: "preview-demo-01", name: "Demo clinic location", address: "100 Demo Way, San Francisco, CA 94105", phone: "(555) 010-1000", hours: "Mon\u2013Fri 8am\u20136pm PT", parking: "Street and garage", transit: "Not specified", accessibility: "Wheelchair accessible", onSiteLab: true, phlebotomy: true, earliestAppt: "Same-day telehealth consults available" }],
    providers: [{ id: "preview-demo-01-prov-1", clinicId: "preview-demo-01", name: "Alex Rivera", credentials: "MD", role: "Medical Director", specialties: "Testosterone Replacement Therapy", yearsExperience: 8, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }, { id: "preview-demo-01-prov-2", clinicId: "preview-demo-01", name: "Jordan Lee", credentials: "NP", role: "Hormone Therapy", specialties: "Testosterone Replacement Therapy", yearsExperience: 11, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }],
    treatments: treatmentRows("preview-demo-01", "Testosterone Replacement Therapy, Hormone Optimization, Telehealth Consultations, Preventive Men's Health").map((t) => ({ ...t, priceRange: "Demo pricing · contact clinic", careFormat: "Hybrid" })),
    reviews: [],
  },
  {
    id: "preview-demo-02",
    name: "Summit Performance Clinic \u2014 Los Angeles",
    slug: "summit-performance-la",
    tagline: "Demonstration clinic profile",
    overview: "Fictional performance and metabolic clinic used to preview directory filters and profile sections. This demonstration profile is fictional and is shown only to preview the Novalyte AI clinic directory experience.",
    logoColor: "emerald",
    city: "Los Angeles",
    state: "CA",
    zip: "90036",
    serviceArea: "Los Angeles and surrounding metro",
    specialties: "Performance Medicine, Medical Weight Loss, GLP-1 Programs, Peptide-related Care",
    capabilities: "Financing available",
    telehealth: true,
    providerTypes: "Physician, Nurse Practitioner",
    phone: "(555) 010-1001",
    email: "demo@summit.example",
    website: null,
    bookingUrl: null,
    hours: "Mon\u2013Sat 9am\u20135pm PT",
    verified: false,
    verificationStatus: "demo",
    acceptingNewPatients: true,
    claimStatus: "not_claimable",
    listingStatus: "demo",
    profileCompleteness: 92,
    initialConsultPrice: 199,
    membershipPrice: 129,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: "Within 3 business days",
    statesServed: "CA",
    languages: "English, Spanish",
    accessibility: "Wheelchair accessible waiting area",
    pricingStatus: "published",
    whatToExpect: "Demonstration itinerary: intake, clinician consult, optional labs, care plan discussion.",
    latitude: 34.0522,
    longitude: -118.2437,
    dataSource: "demo",
    sourceUrl: null,
    lastReviewedAt: "2026-07-20",
    financingAvailable: true,
    inPersonAvailable: true,
    sameDayConsultations: false,
    locations: [{ id: "preview-demo-02-loc-1", clinicId: "preview-demo-02", name: "Demo clinic location", address: "100 Demo Way, Los Angeles, CA 90036", phone: "(555) 010-1001", hours: "Mon\u2013Sat 9am\u20135pm PT", parking: "Street and garage", transit: "Not specified", accessibility: "Wheelchair accessible", onSiteLab: false, phlebotomy: false, earliestAppt: "Within 3 business days" }],
    providers: [{ id: "preview-demo-02-prov-1", clinicId: "preview-demo-02", name: "Sam Patel", credentials: "MD", role: "Performance Medicine", specialties: "Performance Medicine", yearsExperience: 8, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }],
    treatments: treatmentRows("preview-demo-02", "Performance Medicine, Medical Weight Loss, GLP-1 Programs, Peptide-related Care").map((t) => ({ ...t, priceRange: "Demo pricing · contact clinic", careFormat: "Hybrid" })),
    reviews: [],
  },
  {
    id: "preview-demo-03",
    name: "Northstar Longevity Center \u2014 New York",
    slug: "northstar-longevity-nyc",
    tagline: "Demonstration clinic profile",
    overview: "Fictional longevity center demonstrating rich profile content and telehealth capabilities. This demonstration profile is fictional and is shown only to preview the Novalyte AI clinic directory experience.",
    logoColor: "sky",
    city: "New York",
    state: "NY",
    zip: "10017",
    serviceArea: "New York and surrounding metro",
    specialties: "Longevity Medicine, Hormone Optimization, Preventive Men's Health, Telehealth Consultations",
    capabilities: "On-site Lab/Phlebotomy, Financing available",
    telehealth: true,
    providerTypes: "Physician, Nurse Practitioner",
    phone: "(555) 010-1002",
    email: "demo@northstar.example",
    website: null,
    bookingUrl: null,
    hours: "Mon\u2013Fri 7am\u20137pm ET",
    verified: false,
    verificationStatus: "demo",
    acceptingNewPatients: true,
    claimStatus: "not_claimable",
    listingStatus: "demo",
    profileCompleteness: 92,
    initialConsultPrice: 175,
    membershipPrice: 149,
    insuranceAccepted: true,
    hsaFsaAccepted: true,
    earliestAvailability: "Next-day virtual visits",
    statesServed: "NY",
    languages: "English, Spanish",
    accessibility: "Wheelchair accessible waiting area",
    pricingStatus: "published",
    whatToExpect: "Demonstration itinerary: intake, clinician consult, optional labs, care plan discussion.",
    latitude: 40.7128,
    longitude: -74.006,
    dataSource: "demo",
    sourceUrl: null,
    lastReviewedAt: "2026-07-20",
    financingAvailable: false,
    inPersonAvailable: true,
    sameDayConsultations: false,
    locations: [{ id: "preview-demo-03-loc-1", clinicId: "preview-demo-03", name: "Demo clinic location", address: "100 Demo Way, New York, NY 10017", phone: "(555) 010-1002", hours: "Mon\u2013Fri 7am\u20137pm ET", parking: "Street and garage", transit: "Not specified", accessibility: "Wheelchair accessible", onSiteLab: true, phlebotomy: true, earliestAppt: "Next-day virtual visits" }],
    providers: [{ id: "preview-demo-03-prov-1", clinicId: "preview-demo-03", name: "Casey Morgan", credentials: "MD", role: "Longevity", specialties: "Longevity Medicine", yearsExperience: 8, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }, { id: "preview-demo-03-prov-2", clinicId: "preview-demo-03", name: "Riley Chen", credentials: "PA", role: "Preventive Care", specialties: "Longevity Medicine", yearsExperience: 11, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }],
    treatments: treatmentRows("preview-demo-03", "Longevity Medicine, Hormone Optimization, Preventive Men's Health, Telehealth Consultations").map((t) => ({ ...t, priceRange: "Demo pricing · contact clinic", careFormat: "Hybrid" })),
    reviews: [],
  },
  {
    id: "preview-demo-04",
    name: "Elevate Men's Wellness \u2014 Austin",
    slug: "elevate-mens-austin",
    tagline: "Demonstration clinic profile",
    overview: "Fictional Austin men's wellness clinic for previewing treatment and care-format filters. This demonstration profile is fictional and is shown only to preview the Novalyte AI clinic directory experience.",
    logoColor: "violet",
    city: "Austin",
    state: "TX",
    zip: "78704",
    serviceArea: "Austin and surrounding metro",
    specialties: "Sexual Wellness, Erectile Dysfunction, Hair Restoration, Testosterone Replacement Therapy",
    capabilities: "Financing available",
    telehealth: true,
    providerTypes: "Physician, Nurse Practitioner",
    phone: "(555) 010-1003",
    email: "demo@elevate.example",
    website: null,
    bookingUrl: null,
    hours: "Tue\u2013Sat 10am\u20136pm CT",
    verified: false,
    verificationStatus: "demo",
    acceptingNewPatients: true,
    claimStatus: "not_claimable",
    listingStatus: "demo",
    profileCompleteness: 92,
    initialConsultPrice: 125,
    membershipPrice: 79,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: "Same week in-person",
    statesServed: "TX",
    languages: "English, Spanish",
    accessibility: "Wheelchair accessible waiting area",
    pricingStatus: "published",
    whatToExpect: "Demonstration itinerary: intake, clinician consult, optional labs, care plan discussion.",
    latitude: 30.2672,
    longitude: -97.7431,
    dataSource: "demo",
    sourceUrl: null,
    lastReviewedAt: "2026-07-20",
    financingAvailable: true,
    inPersonAvailable: true,
    sameDayConsultations: false,
    locations: [{ id: "preview-demo-04-loc-1", clinicId: "preview-demo-04", name: "Demo clinic location", address: "100 Demo Way, Austin, TX 78704", phone: "(555) 010-1003", hours: "Tue\u2013Sat 10am\u20136pm CT", parking: "Street and garage", transit: "Not specified", accessibility: "Wheelchair accessible", onSiteLab: false, phlebotomy: false, earliestAppt: "Same week in-person" }],
    providers: [{ id: "preview-demo-04-prov-1", clinicId: "preview-demo-04", name: "Taylor Brooks", credentials: "MD", role: "Sexual Wellness", specialties: "Sexual Wellness", yearsExperience: 8, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }],
    treatments: treatmentRows("preview-demo-04", "Sexual Wellness, Erectile Dysfunction, Hair Restoration, Testosterone Replacement Therapy").map((t) => ({ ...t, priceRange: "Demo pricing · contact clinic", careFormat: "Hybrid" })),
    reviews: [],
  },
  {
    id: "preview-demo-05",
    name: "Meridian Performance Medicine \u2014 Miami",
    slug: "meridian-performance-miami",
    tagline: "Demonstration clinic profile",
    overview: "Fictional Miami clinic demonstrating financing, lab, and hybrid care examples. This demonstration profile is fictional and is shown only to preview the Novalyte AI clinic directory experience.",
    logoColor: "amber",
    city: "Miami",
    state: "FL",
    zip: "33132",
    serviceArea: "Miami and surrounding metro",
    specialties: "Performance Medicine, GLP-1 Programs, Onsite Lab, Telehealth Consultations",
    capabilities: "On-site Lab/Phlebotomy, Financing available",
    telehealth: true,
    providerTypes: "Physician, Nurse Practitioner",
    phone: "(555) 010-1004",
    email: "demo@meridian.example",
    website: null,
    bookingUrl: null,
    hours: "Mon\u2013Fri 8am\u20135pm ET",
    verified: false,
    verificationStatus: "demo",
    acceptingNewPatients: true,
    claimStatus: "not_claimable",
    listingStatus: "demo",
    profileCompleteness: 92,
    initialConsultPrice: 159,
    membershipPrice: 109,
    insuranceAccepted: true,
    hsaFsaAccepted: true,
    earliestAvailability: "Same-day consultations",
    statesServed: "FL",
    languages: "English, Spanish",
    accessibility: "Wheelchair accessible waiting area",
    pricingStatus: "published",
    whatToExpect: "Demonstration itinerary: intake, clinician consult, optional labs, care plan discussion.",
    latitude: 25.7617,
    longitude: -80.1918,
    dataSource: "demo",
    sourceUrl: null,
    lastReviewedAt: "2026-07-20",
    financingAvailable: true,
    inPersonAvailable: true,
    sameDayConsultations: true,
    locations: [{ id: "preview-demo-05-loc-1", clinicId: "preview-demo-05", name: "Demo clinic location", address: "100 Demo Way, Miami, FL 33132", phone: "(555) 010-1004", hours: "Mon\u2013Fri 8am\u20135pm ET", parking: "Street and garage", transit: "Not specified", accessibility: "Wheelchair accessible", onSiteLab: true, phlebotomy: true, earliestAppt: "Same-day consultations" }],
    providers: [{ id: "preview-demo-05-prov-1", clinicId: "preview-demo-05", name: "Morgan Ellis", credentials: "MD", role: "Medical Director", specialties: "Performance Medicine", yearsExperience: 8, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }],
    treatments: treatmentRows("preview-demo-05", "Performance Medicine, GLP-1 Programs, Onsite Lab, Telehealth Consultations").map((t) => ({ ...t, priceRange: "Demo pricing · contact clinic", careFormat: "Hybrid" })),
    reviews: [],
  },
  {
    id: "preview-demo-06",
    name: "Apex Men's Health Institute \u2014 Scottsdale",
    slug: "apex-mens-scottsdale",
    tagline: "Demonstration clinic profile",
    overview: "Fictional Scottsdale institute used to preview complete directory profile layouts. This demonstration profile is fictional and is shown only to preview the Novalyte AI clinic directory experience.",
    logoColor: "rose",
    city: "Scottsdale",
    state: "AZ",
    zip: "85255",
    serviceArea: "Scottsdale and surrounding metro",
    specialties: "Hormone Optimization, Longevity Medicine, Men's Primary Care, Peptide-related Care",
    capabilities: "On-site Lab/Phlebotomy, Financing available",
    telehealth: true,
    providerTypes: "Physician, Nurse Practitioner",
    phone: "(555) 010-1005",
    email: "demo@apex.example",
    website: null,
    bookingUrl: null,
    hours: "Mon\u2013Thu 9am\u20136pm MST",
    verified: false,
    verificationStatus: "demo",
    acceptingNewPatients: true,
    claimStatus: "not_claimable",
    listingStatus: "demo",
    profileCompleteness: 92,
    initialConsultPrice: 189,
    membershipPrice: 139,
    insuranceAccepted: false,
    hsaFsaAccepted: true,
    earliestAvailability: "Within 7 days",
    statesServed: "AZ",
    languages: "English, Spanish",
    accessibility: "Wheelchair accessible waiting area",
    pricingStatus: "published",
    whatToExpect: "Demonstration itinerary: intake, clinician consult, optional labs, care plan discussion.",
    latitude: 33.4942,
    longitude: -111.9261,
    dataSource: "demo",
    sourceUrl: null,
    lastReviewedAt: "2026-07-20",
    financingAvailable: true,
    inPersonAvailable: true,
    sameDayConsultations: false,
    locations: [{ id: "preview-demo-06-loc-1", clinicId: "preview-demo-06", name: "Demo clinic location", address: "100 Demo Way, Scottsdale, AZ 85255", phone: "(555) 010-1005", hours: "Mon\u2013Thu 9am\u20136pm MST", parking: "Street and garage", transit: "Not specified", accessibility: "Wheelchair accessible", onSiteLab: true, phlebotomy: true, earliestAppt: "Within 7 days" }],
    providers: [{ id: "preview-demo-06-prov-1", clinicId: "preview-demo-06", name: "Avery Quinn", credentials: "MD", role: "Hormone Optimization", specialties: "Hormone Optimization", yearsExperience: 8, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }, { id: "preview-demo-06-prov-2", clinicId: "preview-demo-06", name: "Jamie Ortiz", credentials: "NP", role: "Men's Primary Care", specialties: "Hormone Optimization", yearsExperience: 11, bio: "Demonstration provider profile for directory preview only.", languages: "English", telehealth: true, avatarUrl: null }],
    treatments: treatmentRows("preview-demo-06", "Hormone Optimization, Longevity Medicine, Men's Primary Care, Peptide-related Care").map((t) => ({ ...t, priceRange: "Demo pricing · contact clinic", careFormat: "Hybrid" })),
    reviews: [],
  },
];

/** Raw unclaimed candidates before source-URL validation (may include placeholders). */
export const PREVIEW_UNCLAIMED_CANDIDATES: PreviewClinic[] = PREVIEW_UNCLAIMED_CLINICS;

/**
 * Sanitized directory dataset: unsourced unclaimed placeholders become demo profiles.
 * Confirmed unclaimed listings (valid public source URL) remain unclaimed.
 */
export const PREVIEW_DIRECTORY_CLINICS: PreviewClinic[] = [
  ...PREVIEW_DEMO_CLINICS,
  ...PREVIEW_UNCLAIMED_CLINICS,
].map((clinic) => sanitizePreviewClinic(clinic));

export const PREVIEW_CONFIRMED_UNCLAIMED_CLINICS: PreviewClinic[] =
  PREVIEW_DIRECTORY_CLINICS.filter((c) => c.listingStatus === "unclaimed");

export const PREVIEW_EFFECTIVE_DEMO_CLINICS: PreviewClinic[] =
  PREVIEW_DIRECTORY_CLINICS.filter((c) => c.listingStatus === "demo");

// Seed-time audit (logs errors/warnings in Node; no throw — UI stays up).
if (typeof process !== "undefined") {
  auditDirectoryClinics(PREVIEW_DIRECTORY_CLINICS);
}

export function getPreviewClinicBySlug(slug: string): PreviewClinic | undefined {
  return PREVIEW_DIRECTORY_CLINICS.find((c) => c.slug === slug);
}

export function getPreviewClinicById(id: string): PreviewClinic | undefined {
  return PREVIEW_DIRECTORY_CLINICS.find((c) => c.id === id);
}

